import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import localfont from "next/font/local";

const mazzard = localfont({
  src: [
    {
      path: "../public/fonts/MazzardM-Light.otf",
      weight: "400",
      style: "normal",
    },

    {
      path: "../public/fonts/MazzardM-Medium.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/MazzardM-Regular.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/MazzardM-SemiBold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-mazzard",
});

const radis = localfont({
  src: "../public/fonts/Radis-Sans.otf",
  variable: "--font-radis",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mazzard.variable + " " + radis.variable}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
